# Generated by Django 4.2.2 on 2023-06-19 11:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название теста')),
                ('description', models.TextField(verbose_name='Описание теста')),
                ('question_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Кол-во вопросов')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Правильный ответ')),
                ('incorrect_answer_1', models.CharField(max_length=255, verbose_name='Неправильный ответ')),
                ('incorrect_answer_2', models.CharField(max_length=255, verbose_name='Неправильный ответ')),
                ('incorrect_answer_3', models.CharField(max_length=255, verbose_name='Неправильный ответ')),
                ('number', models.IntegerField(verbose_name='Номер вопроса')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='main.test', verbose_name='Тест')),
            ],
        ),
    ]
